version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Started Pre-Build stage of Demo front end on `date`
      - npm install
      - npm audit fix
      - npm install -g @angular/cli
  build:
    commands:
      - echo Invalidating CloudFront Cache
      # REPLACE XXXXXXXX WITH THE CLOUDFRONT DISTRIBUTION ID OF YOUR STATIC WEBSITE AND UNCOMMENT THE LINE
      # - aws cloudfront create-invalidation --distribution-id XXXXXXXX --paths "/*"
      - echo started Build stage
      - ng build --prod
      - aws s3 sync ./dist/my-personal-menu s3://demo.mymobile.menu --acl 'public-read' --delete
      # - zip -r demo-site.zip ./dist/my-personal-menu
  post_build:
    commands:
      # - echo Started Post Build stage... Syncing folders
      # - aws s3 sync ./dist/demo-site.zip s3://demo.mymobile.menu --acl 'public-read' --delete
# artifacts:
#   files:
    # - demo-site.zip