version: 0.2
phases:
  install:
    commands:
      - apt-get update
  pre_build:
    commands:
      - npm install
      - npm audit fix
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod              
      - zip -r site.zip dist/user-front-end
      - ls
artifacts:
  files:
    - site.zip